### ISSUE TITLE
missing the static_data/recaptcha files

### ISSUE THREAD

**Issue by arden** [CrabAss/Surakarta-Online#1]
ardendeiMac:Surakarta-Online arden$ node bin/www 
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../static_data/recaptcha'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/arden/data/source/game/Surakarta-Online/routes/index.js:30:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/arden/data/source/game/Surakarta-Online/app.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by CrabAss** [comment]
Please check out the "Tips of Installation" section in the readme file before installation.
